# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("django_commander", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="commandlog",
            name="celery_task_id",
            field=models.IntegerField(null=True),
        )
    ]
