# Generated by Django 2.2.4 on 2019-09-30 19:57

from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('django_commander', '0003_auto_20171221_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='name',
            field=models.CharField(db_index=True, help_text='The name of a command', max_length=400),
        ),
        migrations.AlterField(
            model_name='command',
            name='parameters',
            field=models.TextField(help_text='The parameters used to initialize the command', null=True),
        ),
        migrations.AlterField(
            model_name='commandlog',
            name='command',
            field=models.ForeignKey(help_text='The parent command', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='django_commander.Command'),
        ),
        migrations.AlterField(
            model_name='commandlog',
            name='end_time',
            field=models.DateTimeField(help_text='The time at which the command finished (if applicable)', null=True),
        ),
        migrations.AlterField(
            model_name='commandlog',
            name='error',
            field=picklefield.fields.PickledObjectField(editable=False, help_text='The error returned by the command (if applicable)', null=True),
        ),
        migrations.AlterField(
            model_name='commandlog',
            name='options',
            field=models.TextField(help_text='The options passed to the command', null=True),
        ),
        migrations.AlterField(
            model_name='commandlog',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, help_text='The time at which the command began executing'),
        ),
    ]
