# Generated by Django 2.2.6 on 2019-10-28 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("django_commander", "0005_auto_20191028_1410")]

    operations = [
        migrations.RemoveField(model_name="commandlog", name="options_old"),
        migrations.AlterUniqueTogether(
            name="command", unique_together={("name", "parameters")}
        ),
        migrations.RemoveField(model_name="command", name="parameters_old"),
    ]
