# Generated by Django 3.1.2 on 2021-08-24 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_commander', '0006_auto_20191028_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commandlog',
            name='celery_task_id',
        ),
    ]
