# Generated by Django 3.1.2 on 2020-10-08 16:06

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_commander', '0006_auto_20191028_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='parameters',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='The parameters used to initialize the command'),
        ),
        migrations.AlterField(
            model_name='commandlog',
            name='options',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='The options passed to the command'),
        ),
    ]
