# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-17 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text=b'The name of a loader', max_length=400)),
                ('parameters', models.TextField(help_text=b'The parameters used to initialize the loader', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoaderLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, help_text=b'The time at which the loader began executing')),
                ('end_time', models.DateTimeField(help_text=b'The time at which the loader finished (if applicable)', null=True)),
                ('options', models.TextField(help_text=b'The options passed to the loader', null=True)),
                ('error', picklefield.fields.PickledObjectField(editable=False, help_text=b'The error returned by the loader (if applicable)', null=True)),
                ('loader', models.ForeignKey(help_text=b'The parent loader', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='django_loaders.Loader')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='loader',
            unique_together=set([('name', 'parameters')]),
        ),
    ]
