# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-12 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_commander', '0003_auto_20171221_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('command_logs', models.ManyToManyField(related_name='child_related', to='django_commander.CommandLog')),
                ('commands', models.ManyToManyField(related_name='child_related', to='django_commander.Command')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('command_logs', models.ManyToManyField(related_name='parent_related', to='django_commander.CommandLog')),
                ('commands', models.ManyToManyField(related_name='parent_related', to='django_commander.Command')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='child',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='testapp.Parent'),
        ),
    ]
